<?php

use Illuminate\Database\Seeder;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('districts')->delete();

        $districts = [
            [ 'city_id' => 1, 'district' => 'Seyhan' ],
            [ 'city_id' => 1, 'district' => 'Ceyhan' ],
            [ 'city_id' => 1, 'district' => 'Feke' ],
            [ 'city_id' => 1, 'district' => 'Karaisalı' ],
            [ 'city_id' => 1, 'district' => 'Karataş' ],
            [ 'city_id' => 1, 'district' => 'Kozan' ],
            [ 'city_id' => 1, 'district' => 'Pozantı' ],
            [ 'city_id' => 1, 'district' => 'Saimbeyli' ],
            [ 'city_id' => 1, 'district' => 'Tufanbeyli' ],
            [ 'city_id' => 1, 'district' => 'Yumurtalık' ],
            [ 'city_id' => 1, 'district' => 'Yüreğir' ],
            [ 'city_id' => 1, 'district' => 'Aladağ' ],
            [ 'city_id' => 1, 'district' => 'İmamoğlu' ],
            [ 'city_id' => 1, 'district' => 'Sarıçam' ],
            [ 'city_id' => 1, 'district' => 'Çukurova' ],
            [ 'city_id' => 2, 'district' => 'Adıyaman Merkez' ],
            [ 'city_id' => 2, 'district' => 'Besni' ],
            [ 'city_id' => 2, 'district' => 'Çelikhan' ],
            [ 'city_id' => 2, 'district' => 'Gerger' ],
            [ 'city_id' => 2, 'district' => 'Gölbaşı / Adıyaman' ],
            [ 'city_id' => 2, 'district' => 'Kahta' ],
            [ 'city_id' => 2, 'district' => 'Samsat' ],
            [ 'city_id' => 2, 'district' => 'Sincik' ],
            [ 'city_id' => 2, 'district' => 'Tut' ],
            [ 'city_id' => 3, 'district' => 'Afyonkarahisar Merkez' ],
            [ 'city_id' => 3, 'district' => 'Bolvadin' ],
            [ 'city_id' => 3, 'district' => 'Çay' ],
            [ 'city_id' => 3, 'district' => 'Dazkırı' ],
            [ 'city_id' => 3, 'district' => 'Dinar' ],
            [ 'city_id' => 3, 'district' => 'Emirdağ' ],
            [ 'city_id' => 3, 'district' => 'İhsaniye' ],
            [ 'city_id' => 3, 'district' => 'Sandıklı' ],
            [ 'city_id' => 3, 'district' => 'Sinanpaşa' ],
            [ 'city_id' => 3, 'district' => 'Sultandağı' ],
            [ 'city_id' => 3, 'district' => 'Şuhut' ],
            [ 'city_id' => 3, 'district' => 'Başmakçı' ],
            [ 'city_id' => 3, 'district' => 'Bayat / Afyonkarahisar' ],
            [ 'city_id' => 3, 'district' => 'İscehisar' ],
            [ 'city_id' => 3, 'district' => 'Çobanlar' ],
            [ 'city_id' => 3, 'district' => 'Evciler' ],
            [ 'city_id' => 3, 'district' => 'Hocalar' ],
            [ 'city_id' => 3, 'district' => 'Kızılören' ],
            [ 'city_id' => 4, 'district' => 'Ağrı Merkez' ],
            [ 'city_id' => 4, 'district' => 'Diyadin' ],
            [ 'city_id' => 4, 'district' => 'Doğubayazıt' ],
            [ 'city_id' => 4, 'district' => 'Eleşkirt' ],
            [ 'city_id' => 4, 'district' => 'Hamur' ],
            [ 'city_id' => 4, 'district' => 'Patnos' ],
            [ 'city_id' => 4, 'district' => 'Taşlıçay' ],
            [ 'city_id' => 4, 'district' => 'Tutak' ],
            [ 'city_id' => 5, 'district' => 'Amasya Merkez' ],
            [ 'city_id' => 5, 'district' => 'Göynücek' ],
            [ 'city_id' => 5, 'district' => 'Gümüşhacıköy' ],
            [ 'city_id' => 5, 'district' => 'Merzifon' ],
            [ 'city_id' => 5, 'district' => 'Suluova' ],
            [ 'city_id' => 5, 'district' => 'Taşova' ],
            [ 'city_id' => 5, 'district' => 'Hamamözü' ],
            [ 'city_id' => 6, 'district' => 'Altındağ' ],
            [ 'city_id' => 6, 'district' => 'Ayaş' ],
            [ 'city_id' => 6, 'district' => 'Bala' ],
            [ 'city_id' => 6, 'district' => 'Beypazarı' ],
            [ 'city_id' => 6, 'district' => 'Çamlıdere' ],
            [ 'city_id' => 6, 'district' => 'Çankaya' ],
            [ 'city_id' => 6, 'district' => 'Çubuk' ],
            [ 'city_id' => 6, 'district' => 'Elmadağ' ],
            [ 'city_id' => 6, 'district' => 'Güdül' ],
            [ 'city_id' => 6, 'district' => 'Haymana' ],
            [ 'city_id' => 6, 'district' => 'Kalecik' ],
            [ 'city_id' => 6, 'district' => 'Kızılcahamam' ],
            [ 'city_id' => 6, 'district' => 'Nallıhan' ],
            [ 'city_id' => 6, 'district' => 'Polatlı' ],
            [ 'city_id' => 6, 'district' => 'Şereflikoçhisar' ],
            [ 'city_id' => 6, 'district' => 'Yenimahalle' ],
            [ 'city_id' => 6, 'district' => 'Gölbaşı / Ankara' ],
            [ 'city_id' => 6, 'district' => 'Keçiören' ],
            [ 'city_id' => 6, 'district' => 'Mamak' ],
            [ 'city_id' => 6, 'district' => 'Sincan' ],
            [ 'city_id' => 6, 'district' => 'Kazan' ],
            [ 'city_id' => 6, 'district' => 'Akyurt' ],
            [ 'city_id' => 6, 'district' => 'Etimesgut' ],
            [ 'city_id' => 6, 'district' => 'Evren' ],
            [ 'city_id' => 6, 'district' => 'Pursaklar' ],
            [ 'city_id' => 7, 'district' => 'Akseki' ],
            [ 'city_id' => 7, 'district' => 'Alanya' ],
            [ 'city_id' => 7, 'district' => 'Antalya Merkez' ],
            [ 'city_id' => 7, 'district' => 'Elmalı' ],
            [ 'city_id' => 7, 'district' => 'Finike' ],
            [ 'city_id' => 7, 'district' => 'Gazipaşa' ],
            [ 'city_id' => 7, 'district' => 'Gündoğmuş' ],
            [ 'city_id' => 7, 'district' => 'Kaş' ],
            [ 'city_id' => 7, 'district' => 'Korkuteli' ],
            [ 'city_id' => 7, 'district' => 'Kumluca' ],
            [ 'city_id' => 7, 'district' => 'Manavgat' ],
            [ 'city_id' => 7, 'district' => 'Serik' ],
            [ 'city_id' => 7, 'district' => 'Demre' ],
            [ 'city_id' => 7, 'district' => 'İbradı' ],
            [ 'city_id' => 7, 'district' => 'Kemer / Antalya' ],
            [ 'city_id' => 7, 'district' => 'Aksu / Antalya' ],
            [ 'city_id' => 7, 'district' => 'Döşemealtı' ],
            [ 'city_id' => 7, 'district' => 'Kepez' ],
            [ 'city_id' => 7, 'district' => 'Konyaaltı' ],
            [ 'city_id' => 7, 'district' => 'Muratpaşa' ],
            [ 'city_id' => 8, 'district' => 'Ardanuç' ],
            [ 'city_id' => 8, 'district' => 'Arhavi' ],
            [ 'city_id' => 8, 'district' => 'Artvin Merkez' ],
            [ 'city_id' => 8, 'district' => 'Borçka' ],
            [ 'city_id' => 8, 'district' => 'Hopa' ],
            [ 'city_id' => 8, 'district' => 'Şavşat' ],
            [ 'city_id' => 8, 'district' => 'Yusufeli' ],
            [ 'city_id' => 8, 'district' => 'Murgul' ],
            [ 'city_id' => 9, 'district' => 'Aydın Merkez' ],
            [ 'city_id' => 9, 'district' => 'Bozdoğan' ],
            [ 'city_id' => 9, 'district' => 'Çine' ],
            [ 'city_id' => 9, 'district' => 'Germencik' ],
            [ 'city_id' => 9, 'district' => 'Karacasu' ],
            [ 'city_id' => 9, 'district' => 'Koçarlı' ],
            [ 'city_id' => 9, 'district' => 'Kuşadası' ],
            [ 'city_id' => 9, 'district' => 'Kuyucak' ],
            [ 'city_id' => 9, 'district' => 'Nazilli' ],
            [ 'city_id' => 9, 'district' => 'Söke' ],
            [ 'city_id' => 9, 'district' => 'Sultanhisar' ],
            [ 'city_id' => 9, 'district' => 'Yenipazar / Aydın' ],
            [ 'city_id' => 9, 'district' => 'Buharkent' ],
            [ 'city_id' => 9, 'district' => 'İncirliova' ],
            [ 'city_id' => 9, 'district' => 'Karpuzlu' ],
            [ 'city_id' => 9, 'district' => 'Köşk' ],
            [ 'city_id' => 9, 'district' => 'Didim' ],
            [ 'city_id' => 9, 'district' => 'Efeler' ],
            [ 'city_id' => 10, 'district' => 'Ayvalık' ],
            [ 'city_id' => 10, 'district' => 'Balıkesir Merkez' ],
            [ 'city_id' => 10, 'district' => 'Balya' ],
            [ 'city_id' => 10, 'district' => 'Bandırma' ],
            [ 'city_id' => 10, 'district' => 'Bigadiç' ],
            [ 'city_id' => 10, 'district' => 'Burhaniye' ],
            [ 'city_id' => 10, 'district' => 'Dursunbey' ],
            [ 'city_id' => 10, 'district' => 'Edremit / Balıkesir' ],
            [ 'city_id' => 10, 'district' => 'Erdek' ],
            [ 'city_id' => 10, 'district' => 'Gönen / Balıkesir' ],
            [ 'city_id' => 10, 'district' => 'Havran' ],
            [ 'city_id' => 10, 'district' => 'İvrindi' ],
            [ 'city_id' => 10, 'district' => 'Kepsut' ],
            [ 'city_id' => 10, 'district' => 'Manyas' ],
            [ 'city_id' => 10, 'district' => 'Savaştepe' ],
            [ 'city_id' => 10, 'district' => 'Sındırgı' ],
            [ 'city_id' => 10, 'district' => 'Susurluk' ],
            [ 'city_id' => 10, 'district' => 'Marmara' ],
            [ 'city_id' => 10, 'district' => 'Gömeç' ],
            [ 'city_id' => 10, 'district' => 'Altıeylül' ],
            [ 'city_id' => 10, 'district' => 'Karesi' ],
            [ 'city_id' => 11, 'district' => 'Bilecik Merkez' ],
            [ 'city_id' => 11, 'district' => 'Bozüyük' ],
            [ 'city_id' => 11, 'district' => 'Gölpazarı' ],
            [ 'city_id' => 11, 'district' => 'Osmaneli' ],
            [ 'city_id' => 11, 'district' => 'Pazaryeri' ],
            [ 'city_id' => 11, 'district' => 'Söğüt' ],
            [ 'city_id' => 11, 'district' => 'Yenipazar / Bilecik' ],
            [ 'city_id' => 11, 'district' => 'İnhisar' ],
            [ 'city_id' => 12, 'district' => 'Bingöl Merkez' ],
            [ 'city_id' => 12, 'district' => 'Genç' ],
            [ 'city_id' => 12, 'district' => 'Karlıova' ],
            [ 'city_id' => 12, 'district' => 'Kiğı' ],
            [ 'city_id' => 12, 'district' => 'Solhan' ],
            [ 'city_id' => 12, 'district' => 'Adaklı' ],
            [ 'city_id' => 12, 'district' => 'Yayladere' ],
            [ 'city_id' => 12, 'district' => 'Yedisu' ],
            [ 'city_id' => 13, 'district' => 'Adilcevaz' ],
            [ 'city_id' => 13, 'district' => 'Ahlat' ],
            [ 'city_id' => 13, 'district' => 'Bitlis Merkez' ],
            [ 'city_id' => 13, 'district' => 'Hizan' ],
            [ 'city_id' => 13, 'district' => 'Mutki' ],
            [ 'city_id' => 13, 'district' => 'Tatvan' ],
            [ 'city_id' => 13, 'district' => 'Güroymak' ],
            [ 'city_id' => 14, 'district' => 'Bolu Merkez' ],
            [ 'city_id' => 14, 'district' => 'Gerede' ],
            [ 'city_id' => 14, 'district' => 'Göynük' ],
            [ 'city_id' => 14, 'district' => 'Kıbrıscık' ],
            [ 'city_id' => 14, 'district' => 'Mengen' ],
            [ 'city_id' => 14, 'district' => 'Mudurnu' ],
            [ 'city_id' => 14, 'district' => 'Seben' ],
            [ 'city_id' => 14, 'district' => 'Dörtdivan' ],
            [ 'city_id' => 14, 'district' => 'Yeniçağa' ],
            [ 'city_id' => 15, 'district' => 'Ağlasun' ],
            [ 'city_id' => 15, 'district' => 'Bucak' ],
            [ 'city_id' => 15, 'district' => 'Burdur Merkez' ],
            [ 'city_id' => 15, 'district' => 'Gölhisar' ],
            [ 'city_id' => 15, 'district' => 'Tefenni' ],
            [ 'city_id' => 15, 'district' => 'Yeşilova' ],
            [ 'city_id' => 15, 'district' => 'Karamanlı' ],
            [ 'city_id' => 15, 'district' => 'Kemer / Burdur' ],
            [ 'city_id' => 15, 'district' => 'Altınyayla / Burdur' ],
            [ 'city_id' => 15, 'district' => 'Çavdır' ],
            [ 'city_id' => 15, 'district' => 'Çeltikçi' ],
            [ 'city_id' => 16, 'district' => 'Gemlik' ],
            [ 'city_id' => 16, 'district' => 'İnegöl' ],
            [ 'city_id' => 16, 'district' => 'İznik' ],
            [ 'city_id' => 16, 'district' => 'Karacabey' ],
            [ 'city_id' => 16, 'district' => 'Keles' ],
            [ 'city_id' => 16, 'district' => 'Mudanya' ],
            [ 'city_id' => 16, 'district' => 'Mustafakemalpaşa' ],
            [ 'city_id' => 16, 'district' => 'Orhaneli' ],
            [ 'city_id' => 16, 'district' => 'Orhangazi' ],
            [ 'city_id' => 16, 'district' => 'Yenişehir / Bursa' ],
            [ 'city_id' => 16, 'district' => 'Büyükorhan' ],
            [ 'city_id' => 16, 'district' => 'Harmancık' ],
            [ 'city_id' => 16, 'district' => 'Nilüfer' ],
            [ 'city_id' => 16, 'district' => 'Osmangazi' ],
            [ 'city_id' => 16, 'district' => 'Yıldırım' ],
            [ 'city_id' => 16, 'district' => 'Gürsu' ],
            [ 'city_id' => 16, 'district' => 'Kestel' ],
            [ 'city_id' => 17, 'district' => 'Ayvacık / Çanakkale' ],
            [ 'city_id' => 17, 'district' => 'Bayramiç' ],
            [ 'city_id' => 17, 'district' => 'Biga' ],
            [ 'city_id' => 17, 'district' => 'Bozcaada' ],
            [ 'city_id' => 17, 'district' => 'Çan' ],
            [ 'city_id' => 17, 'district' => 'Çanakkale Merkez' ],
            [ 'city_id' => 17, 'district' => 'Eceabat' ],
            [ 'city_id' => 17, 'district' => 'Ezine' ],
            [ 'city_id' => 17, 'district' => 'Gelibolu' ],
            [ 'city_id' => 17, 'district' => 'Gökçeada' ],
            [ 'city_id' => 17, 'district' => 'Lapseki' ],
            [ 'city_id' => 17, 'district' => 'Yenice / Çanakkale' ],
            [ 'city_id' => 18, 'district' => 'Çankırı Merkez' ],
            [ 'city_id' => 18, 'district' => 'Çerkeş' ],
            [ 'city_id' => 18, 'district' => 'Eldivan' ],
            [ 'city_id' => 18, 'district' => 'Ilgaz' ],
            [ 'city_id' => 18, 'district' => 'Kurşunlu' ],
            [ 'city_id' => 18, 'district' => 'Orta' ],
            [ 'city_id' => 18, 'district' => 'Şabanözü' ],
            [ 'city_id' => 18, 'district' => 'Yapraklı' ],
            [ 'city_id' => 18, 'district' => 'Atkaracalar' ],
            [ 'city_id' => 18, 'district' => 'Kızılırmak' ],
            [ 'city_id' => 18, 'district' => 'Bayramören' ],
            [ 'city_id' => 18, 'district' => 'Korgun' ],
            [ 'city_id' => 19, 'district' => 'Alaca' ],
            [ 'city_id' => 19, 'district' => 'Bayat / Çorum' ],
            [ 'city_id' => 19, 'district' => 'Çorum Merkez' ],
            [ 'city_id' => 19, 'district' => 'İskilip' ],
            [ 'city_id' => 19, 'district' => 'Kargı' ],
            [ 'city_id' => 19, 'district' => 'Mecitözü' ],
            [ 'city_id' => 19, 'district' => 'Ortaköy / Çorum' ],
            [ 'city_id' => 19, 'district' => 'Osmancık' ],
            [ 'city_id' => 19, 'district' => 'Sungurlu' ],
            [ 'city_id' => 19, 'district' => 'Boğazkale' ],
            [ 'city_id' => 19, 'district' => 'Uğurludağ' ],
            [ 'city_id' => 19, 'district' => 'Dodurga' ],
            [ 'city_id' => 19, 'district' => 'Laçin' ],
            [ 'city_id' => 19, 'district' => 'Oğuzlar' ],
            [ 'city_id' => 20, 'district' => 'Acıpayam' ],
            [ 'city_id' => 20, 'district' => 'Buldan' ],
            [ 'city_id' => 20, 'district' => 'Çal' ],
            [ 'city_id' => 20, 'district' => 'Çameli' ],
            [ 'city_id' => 20, 'district' => 'Çardak' ],
            [ 'city_id' => 20, 'district' => 'Çivril' ],
            [ 'city_id' => 20, 'district' => 'Denizli Merkez' ],
            [ 'city_id' => 20, 'district' => 'Güney' ],
            [ 'city_id' => 20, 'district' => 'Kale / Denizli' ],
            [ 'city_id' => 20, 'district' => 'Sarayköy' ],
            [ 'city_id' => 20, 'district' => 'Tavas' ],
            [ 'city_id' => 20, 'district' => 'Babadağ' ],
            [ 'city_id' => 20, 'district' => 'Bekilli' ],
            [ 'city_id' => 20, 'district' => 'Honaz' ],
            [ 'city_id' => 20, 'district' => 'Serinhisar' ],
            [ 'city_id' => 20, 'district' => 'Pamukkale' ],
            [ 'city_id' => 20, 'district' => 'Baklan' ],
            [ 'city_id' => 20, 'district' => 'Beyağaç' ],
            [ 'city_id' => 20, 'district' => 'Bozkurt / Denizli' ],
            [ 'city_id' => 20, 'district' => 'Merkezefendi' ],
            [ 'city_id' => 21, 'district' => 'Bismil' ],
            [ 'city_id' => 21, 'district' => 'Çermik' ],
            [ 'city_id' => 21, 'district' => 'Çınar' ],
            [ 'city_id' => 21, 'district' => 'Çüngüş' ],
            [ 'city_id' => 21, 'district' => 'Dicle' ],
            [ 'city_id' => 21, 'district' => 'Diyarbakır Merkez' ],
            [ 'city_id' => 21, 'district' => 'Ergani' ],
            [ 'city_id' => 21, 'district' => 'Hani' ],
            [ 'city_id' => 21, 'district' => 'Hazro' ],
            [ 'city_id' => 21, 'district' => 'Kulp' ],
            [ 'city_id' => 21, 'district' => 'Lice' ],
            [ 'city_id' => 21, 'district' => 'Silvan' ],
            [ 'city_id' => 21, 'district' => 'Eğil' ],
            [ 'city_id' => 21, 'district' => 'Kocaköy' ],
            [ 'city_id' => 21, 'district' => 'Bağlar' ],
            [ 'city_id' => 21, 'district' => 'Kayapınar' ],
            [ 'city_id' => 21, 'district' => 'Sur' ],
            [ 'city_id' => 21, 'district' => 'Yenişehir / Diyarbakır' ],
            [ 'city_id' => 22, 'district' => 'Edirne Merkez' ],
            [ 'city_id' => 22, 'district' => 'Enez' ],
            [ 'city_id' => 22, 'district' => 'Havsa' ],
            [ 'city_id' => 22, 'district' => 'İpsala' ],
            [ 'city_id' => 22, 'district' => 'Keşan' ],
            [ 'city_id' => 22, 'district' => 'Lalapaşa' ],
            [ 'city_id' => 22, 'district' => 'Meriç' ],
            [ 'city_id' => 22, 'district' => 'Uzunköprü' ],
            [ 'city_id' => 22, 'district' => 'Süloğlu' ],
            [ 'city_id' => 23, 'district' => 'Ağın' ],
            [ 'city_id' => 23, 'district' => 'Baskil' ],
            [ 'city_id' => 23, 'district' => 'Elazığ Merkez' ],
            [ 'city_id' => 23, 'district' => 'Karakoçan' ],
            [ 'city_id' => 23, 'district' => 'Keban' ],
            [ 'city_id' => 23, 'district' => 'Maden' ],
            [ 'city_id' => 23, 'district' => 'Palu' ],
            [ 'city_id' => 23, 'district' => 'Sivrice' ],
            [ 'city_id' => 23, 'district' => 'Arıcak' ],
            [ 'city_id' => 23, 'district' => 'Kovancılar' ],
            [ 'city_id' => 23, 'district' => 'Alacakaya' ],
            [ 'city_id' => 24, 'district' => 'Çayırlı' ],
            [ 'city_id' => 24, 'district' => 'Erzincan Merkez' ],
            [ 'city_id' => 24, 'district' => 'İliç' ],
            [ 'city_id' => 24, 'district' => 'Kemah' ],
            [ 'city_id' => 24, 'district' => 'Kemaliye' ],
            [ 'city_id' => 24, 'district' => 'Refahiye' ],
            [ 'city_id' => 24, 'district' => 'Tercan' ],
            [ 'city_id' => 24, 'district' => 'Üzümlü' ],
            [ 'city_id' => 24, 'district' => 'Otlukbeli' ],
            [ 'city_id' => 25, 'district' => 'Aşkale' ],
            [ 'city_id' => 25, 'district' => 'Çat' ],
            [ 'city_id' => 25, 'district' => 'Erzurum Merkez' ],
            [ 'city_id' => 25, 'district' => 'Hınıs' ],
            [ 'city_id' => 25, 'district' => 'Horasan' ],
            [ 'city_id' => 25, 'district' => 'İspir' ],
            [ 'city_id' => 25, 'district' => 'Karayazı' ],
            [ 'city_id' => 25, 'district' => 'Narman' ],
            [ 'city_id' => 25, 'district' => 'Oltu' ],
            [ 'city_id' => 25, 'district' => 'Olur' ],
            [ 'city_id' => 25, 'district' => 'Pasinler' ],
            [ 'city_id' => 25, 'district' => 'Şenkaya' ],
            [ 'city_id' => 25, 'district' => 'Tekman' ],
            [ 'city_id' => 25, 'district' => 'Tortum' ],
            [ 'city_id' => 25, 'district' => 'Karaçoban' ],
            [ 'city_id' => 25, 'district' => 'Uzundere' ],
            [ 'city_id' => 25, 'district' => 'Pazaryolu' ],
            [ 'city_id' => 25, 'district' => 'Aziziye' ],
            [ 'city_id' => 25, 'district' => 'Köprüköy' ],
            [ 'city_id' => 25, 'district' => 'Palandöken' ],
            [ 'city_id' => 25, 'district' => 'Yakutiye' ],
            [ 'city_id' => 26, 'district' => 'Çifteler' ],
            [ 'city_id' => 26, 'district' => 'Eskişehir Merkez' ],
            [ 'city_id' => 26, 'district' => 'Mahmudiye' ],
            [ 'city_id' => 26, 'district' => 'Mihalıççık' ],
            [ 'city_id' => 26, 'district' => 'Sarıcakaya' ],
            [ 'city_id' => 26, 'district' => 'Seyitgazi' ],
            [ 'city_id' => 26, 'district' => 'Sivrihisar' ],
            [ 'city_id' => 26, 'district' => 'Alpu' ],
            [ 'city_id' => 26, 'district' => 'Beylikova' ],
            [ 'city_id' => 26, 'district' => 'İnönü' ],
            [ 'city_id' => 26, 'district' => 'Günyüzü' ],
            [ 'city_id' => 26, 'district' => 'Han' ],
            [ 'city_id' => 26, 'district' => 'Mihalgazi' ],
            [ 'city_id' => 26, 'district' => 'Odunpazarı' ],
            [ 'city_id' => 26, 'district' => 'Tepebaşı' ],
            [ 'city_id' => 27, 'district' => 'Araban' ],
            [ 'city_id' => 27, 'district' => 'İslahiye' ],
            [ 'city_id' => 27, 'district' => 'Nizip' ],
            [ 'city_id' => 27, 'district' => 'Oğuzeli' ],
            [ 'city_id' => 27, 'district' => 'Yavuzeli' ],
            [ 'city_id' => 27, 'district' => 'Şahinbey' ],
            [ 'city_id' => 27, 'district' => 'Şehitkamil' ],
            [ 'city_id' => 27, 'district' => 'Karkamış' ],
            [ 'city_id' => 27, 'district' => 'Nurdağı' ],
            [ 'city_id' => 28, 'district' => 'Alucra' ],
            [ 'city_id' => 28, 'district' => 'Bulancak' ],
            [ 'city_id' => 28, 'district' => 'Dereli' ],
            [ 'city_id' => 28, 'district' => 'Espiye' ],
            [ 'city_id' => 28, 'district' => 'Eynesil' ],
            [ 'city_id' => 28, 'district' => 'Giresun Merkez' ],
            [ 'city_id' => 28, 'district' => 'Görele' ],
            [ 'city_id' => 28, 'district' => 'Keşap' ],
            [ 'city_id' => 28, 'district' => 'Şebinkarahisar' ],
            [ 'city_id' => 28, 'district' => 'Tirebolu' ],
            [ 'city_id' => 28, 'district' => 'Piraziz' ],
            [ 'city_id' => 28, 'district' => 'Yağlıdere' ],
            [ 'city_id' => 28, 'district' => 'Çamoluk' ],
            [ 'city_id' => 28, 'district' => 'Çanakçı' ],
            [ 'city_id' => 28, 'district' => 'Doğankent' ],
            [ 'city_id' => 28, 'district' => 'Güce' ],
            [ 'city_id' => 29, 'district' => 'Gümüşhane Merkez' ],
            [ 'city_id' => 29, 'district' => 'Kelkit' ],
            [ 'city_id' => 29, 'district' => 'Şiran' ],
            [ 'city_id' => 29, 'district' => 'Torul' ],
            [ 'city_id' => 29, 'district' => 'Köse' ],
            [ 'city_id' => 29, 'district' => 'Kürtün' ],
            [ 'city_id' => 30, 'district' => 'Çukurca' ],
            [ 'city_id' => 30, 'district' => 'Hakkari Merkez' ],
            [ 'city_id' => 30, 'district' => 'Şemdinli' ],
            [ 'city_id' => 30, 'district' => 'Yüksekova' ],
            [ 'city_id' => 31, 'district' => 'Altınözü' ],
            [ 'city_id' => 31, 'district' => 'Dörtyol' ],
            [ 'city_id' => 31, 'district' => 'Hassa' ],
            [ 'city_id' => 31, 'district' => 'Hatay Merkez' ],
            [ 'city_id' => 31, 'district' => 'İskenderun' ],
            [ 'city_id' => 31, 'district' => 'Kırıkhan' ],
            [ 'city_id' => 31, 'district' => 'Reyhanlı' ],
            [ 'city_id' => 31, 'district' => 'Samandağ' ],
            [ 'city_id' => 31, 'district' => 'Yayladağı' ],
            [ 'city_id' => 31, 'district' => 'Erzin' ],
            [ 'city_id' => 31, 'district' => 'Belen' ],
            [ 'city_id' => 31, 'district' => 'Kumlu' ],
            [ 'city_id' => 31, 'district' => 'Antakya' ],
            [ 'city_id' => 31, 'district' => 'Arsuz' ],
            [ 'city_id' => 31, 'district' => 'Defne' ],
            [ 'city_id' => 31, 'district' => 'Payas' ],
            [ 'city_id' => 32, 'district' => 'Atabey' ],
            [ 'city_id' => 32, 'district' => 'Eğirdir' ],
            [ 'city_id' => 32, 'district' => 'Gelendost' ],
            [ 'city_id' => 32, 'district' => 'Isparta Merkez' ],
            [ 'city_id' => 32, 'district' => 'Keçiborlu' ],
            [ 'city_id' => 32, 'district' => 'Senirkent' ],
            [ 'city_id' => 32, 'district' => 'Sütçüler' ],
            [ 'city_id' => 32, 'district' => 'Şarkikaraağaç' ],
            [ 'city_id' => 32, 'district' => 'Uluborlu' ],
            [ 'city_id' => 32, 'district' => 'Yalvaç' ],
            [ 'city_id' => 32, 'district' => 'Aksu / Isparta' ],
            [ 'city_id' => 32, 'district' => 'Gönen / Isparta' ],
            [ 'city_id' => 32, 'district' => 'Yenişarbademli' ],
            [ 'city_id' => 33, 'district' => 'Anamur' ],
            [ 'city_id' => 33, 'district' => 'Erdemli' ],
            [ 'city_id' => 33, 'district' => 'Gülnar' ],
            [ 'city_id' => 33, 'district' => 'Mersin Merkez' ],
            [ 'city_id' => 33, 'district' => 'Mut' ],
            [ 'city_id' => 33, 'district' => 'Silifke' ],
            [ 'city_id' => 33, 'district' => 'Tarsus' ],
            [ 'city_id' => 33, 'district' => 'Aydıncık / Mersin' ],
            [ 'city_id' => 33, 'district' => 'Bozyazı' ],
            [ 'city_id' => 33, 'district' => 'Çamlıyayla' ],
            [ 'city_id' => 33, 'district' => 'Akdeniz' ],
            [ 'city_id' => 33, 'district' => 'Mezitli' ],
            [ 'city_id' => 33, 'district' => 'Toroslar' ],
            [ 'city_id' => 33, 'district' => 'Yenişehir / Mersin' ],
            [ 'city_id' => 34, 'district' => 'Adalar' ],
            [ 'city_id' => 34, 'district' => 'Bakırköy' ],
            [ 'city_id' => 34, 'district' => 'Beşiktaş' ],
            [ 'city_id' => 34, 'district' => 'Beykoz' ],
            [ 'city_id' => 34, 'district' => 'Beyoğlu' ],
            [ 'city_id' => 34, 'district' => 'Çatalca' ],
            [ 'city_id' => 34, 'district' => 'Eminönü' ],
            [ 'city_id' => 34, 'district' => 'Eyüp' ],
            [ 'city_id' => 34, 'district' => 'Fatih' ],
            [ 'city_id' => 34, 'district' => 'Gaziosmanpaşa' ],
            [ 'city_id' => 34, 'district' => 'Kadıköy' ],
            [ 'city_id' => 34, 'district' => 'Kartal' ],
            [ 'city_id' => 34, 'district' => 'Sarıyer' ],
            [ 'city_id' => 34, 'district' => 'Silivri' ],
            [ 'city_id' => 34, 'district' => 'Şile' ],
            [ 'city_id' => 34, 'district' => 'Şişli' ],
            [ 'city_id' => 34, 'district' => 'Üsküdar' ],
            [ 'city_id' => 34, 'district' => 'Zeytinburnu' ],
            [ 'city_id' => 34, 'district' => 'Büyükçekmece' ],
            [ 'city_id' => 34, 'district' => 'Kağıthane' ],
            [ 'city_id' => 34, 'district' => 'Küçükçekmece' ],
            [ 'city_id' => 34, 'district' => 'Pendik' ],
            [ 'city_id' => 34, 'district' => 'Ümraniye' ],
            [ 'city_id' => 34, 'district' => 'Bayrampaşa' ],
            [ 'city_id' => 34, 'district' => 'Avcılar' ],
            [ 'city_id' => 34, 'district' => 'Bağcılar' ],
            [ 'city_id' => 34, 'district' => 'Bahçelievler' ],
            [ 'city_id' => 34, 'district' => 'Güngören' ],
            [ 'city_id' => 34, 'district' => 'Maltepe' ],
            [ 'city_id' => 34, 'district' => 'Sultanbeyli' ],
            [ 'city_id' => 34, 'district' => 'Tuzla' ],
            [ 'city_id' => 34, 'district' => 'Esenler' ],
            [ 'city_id' => 34, 'district' => 'Arnavutköy' ],
            [ 'city_id' => 34, 'district' => 'Ataşehir' ],
            [ 'city_id' => 34, 'district' => 'Başakşehir' ],
            [ 'city_id' => 34, 'district' => 'Beylikdüzü' ],
            [ 'city_id' => 34, 'district' => 'Çekmeköy' ],
            [ 'city_id' => 34, 'district' => 'Esenyurt' ],
            [ 'city_id' => 34, 'district' => 'Sancaktepe' ],
            [ 'city_id' => 34, 'district' => 'Sultangazi' ],
            [ 'city_id' => 35, 'district' => 'Aliağa' ],
            [ 'city_id' => 35, 'district' => 'Bayındır' ],
            [ 'city_id' => 35, 'district' => 'Bergama' ],
            [ 'city_id' => 35, 'district' => 'Bornova' ],
            [ 'city_id' => 35, 'district' => 'Çeşme' ],
            [ 'city_id' => 35, 'district' => 'Dikili' ],
            [ 'city_id' => 35, 'district' => 'Foça' ],
            [ 'city_id' => 35, 'district' => 'Karaburun' ],
            [ 'city_id' => 35, 'district' => 'Karşıyaka' ],
            [ 'city_id' => 35, 'district' => 'Kemalpaşa' ],
            [ 'city_id' => 35, 'district' => 'Kınık' ],
            [ 'city_id' => 35, 'district' => 'Kiraz' ],
            [ 'city_id' => 35, 'district' => 'Menemen' ],
            [ 'city_id' => 35, 'district' => 'Ödemiş' ],
            [ 'city_id' => 35, 'district' => 'Seferihisar' ],
            [ 'city_id' => 35, 'district' => 'Selçuk' ],
            [ 'city_id' => 35, 'district' => 'Tire' ],
            [ 'city_id' => 35, 'district' => 'Torbalı' ],
            [ 'city_id' => 35, 'district' => 'Urla' ],
            [ 'city_id' => 35, 'district' => 'Beydağ' ],
            [ 'city_id' => 35, 'district' => 'Buca' ],
            [ 'city_id' => 35, 'district' => 'Konak' ],
            [ 'city_id' => 35, 'district' => 'Menderes' ],
            [ 'city_id' => 35, 'district' => 'Balçova' ],
            [ 'city_id' => 35, 'district' => 'Çiğli' ],
            [ 'city_id' => 35, 'district' => 'Gaziemir' ],
            [ 'city_id' => 35, 'district' => 'Narlıdere' ],
            [ 'city_id' => 35, 'district' => 'Güzelbahçe' ],
            [ 'city_id' => 35, 'district' => 'Bayraklı' ],
            [ 'city_id' => 35, 'district' => 'Karabağlar' ],
            [ 'city_id' => 36, 'district' => 'Arpaçay' ],
            [ 'city_id' => 36, 'district' => 'Digor' ],
            [ 'city_id' => 36, 'district' => 'Kağızman' ],
            [ 'city_id' => 36, 'district' => 'Kars Merkez' ],
            [ 'city_id' => 36, 'district' => 'Sarıkamış' ],
            [ 'city_id' => 36, 'district' => 'Selim' ],
            [ 'city_id' => 36, 'district' => 'Susuz' ],
            [ 'city_id' => 36, 'district' => 'Akyaka' ],
            [ 'city_id' => 37, 'district' => 'Abana' ],
            [ 'city_id' => 37, 'district' => 'Araç' ],
            [ 'city_id' => 37, 'district' => 'Azdavay' ],
            [ 'city_id' => 37, 'district' => 'Bozkurt / Kastamonu' ],
            [ 'city_id' => 37, 'district' => 'Cide' ],
            [ 'city_id' => 37, 'district' => 'Çatalzeytin' ],
            [ 'city_id' => 37, 'district' => 'Daday' ],
            [ 'city_id' => 37, 'district' => 'Devrekani' ],
            [ 'city_id' => 37, 'district' => 'İnebolu' ],
            [ 'city_id' => 37, 'district' => 'Kastamonu Merkez' ],
            [ 'city_id' => 37, 'district' => 'Küre' ],
            [ 'city_id' => 37, 'district' => 'Taşköprü' ],
            [ 'city_id' => 37, 'district' => 'Tosya' ],
            [ 'city_id' => 37, 'district' => 'İhsangazi' ],
            [ 'city_id' => 37, 'district' => 'Pınarbaşı / Kastamonu' ],
            [ 'city_id' => 37, 'district' => 'Şenpazar' ],
            [ 'city_id' => 37, 'district' => 'Ağlı' ],
            [ 'city_id' => 37, 'district' => 'Doğanyurt' ],
            [ 'city_id' => 37, 'district' => 'Hanönü' ],
            [ 'city_id' => 37, 'district' => 'Seydiler' ],
            [ 'city_id' => 38, 'district' => 'Bünyan' ],
            [ 'city_id' => 38, 'district' => 'Develi' ],
            [ 'city_id' => 38, 'district' => 'Felahiye' ],
            [ 'city_id' => 38, 'district' => 'İncesu' ],
            [ 'city_id' => 38, 'district' => 'Pınarbaşı / Kayseri' ],
            [ 'city_id' => 38, 'district' => 'Sarıoğlan' ],
            [ 'city_id' => 38, 'district' => 'Sarız' ],
            [ 'city_id' => 38, 'district' => 'Tomarza' ],
            [ 'city_id' => 38, 'district' => 'Yahyalı' ],
            [ 'city_id' => 38, 'district' => 'Yeşilhisar' ],
            [ 'city_id' => 38, 'district' => 'Akkışla' ],
            [ 'city_id' => 38, 'district' => 'Talas' ],
            [ 'city_id' => 38, 'district' => 'Kocasinan' ],
            [ 'city_id' => 38, 'district' => 'Melikgazi' ],
            [ 'city_id' => 38, 'district' => 'Hacılar' ],
            [ 'city_id' => 38, 'district' => 'Özvatan' ],
            [ 'city_id' => 39, 'district' => 'Babaeski' ],
            [ 'city_id' => 39, 'district' => 'Demirköy' ],
            [ 'city_id' => 39, 'district' => 'Kırklareli Merkez' ],
            [ 'city_id' => 39, 'district' => 'Kofçaz' ],
            [ 'city_id' => 39, 'district' => 'Lüleburgaz' ],
            [ 'city_id' => 39, 'district' => 'Pehlivanköy' ],
            [ 'city_id' => 39, 'district' => 'Pınarhisar' ],
            [ 'city_id' => 39, 'district' => 'Vize' ],
            [ 'city_id' => 40, 'district' => 'Çiçekdağı' ],
            [ 'city_id' => 40, 'district' => 'Kaman' ],
            [ 'city_id' => 40, 'district' => 'Kırşehir Merkez' ],
            [ 'city_id' => 40, 'district' => 'Mucur' ],
            [ 'city_id' => 40, 'district' => 'Akpınar' ],
            [ 'city_id' => 40, 'district' => 'Akçakent' ],
            [ 'city_id' => 40, 'district' => 'Boztepe' ],
            [ 'city_id' => 41, 'district' => 'Gebze' ],
            [ 'city_id' => 41, 'district' => 'Gölcük' ],
            [ 'city_id' => 41, 'district' => 'Kandıra' ],
            [ 'city_id' => 41, 'district' => 'Karamürsel' ],
            [ 'city_id' => 41, 'district' => 'Kocaeli Merkez' ],
            [ 'city_id' => 41, 'district' => 'Körfez' ],
            [ 'city_id' => 41, 'district' => 'Derince' ],
            [ 'city_id' => 41, 'district' => 'Başiskele' ],
            [ 'city_id' => 41, 'district' => 'Çayırova' ],
            [ 'city_id' => 41, 'district' => 'Darıca' ],
            [ 'city_id' => 41, 'district' => 'Dilovası' ],
            [ 'city_id' => 41, 'district' => 'İzmit' ],
            [ 'city_id' => 41, 'district' => 'Kartepe' ],
            [ 'city_id' => 42, 'district' => 'Akşehir' ],
            [ 'city_id' => 42, 'district' => 'Beyşehir' ],
            [ 'city_id' => 42, 'district' => 'Bozkır' ],
            [ 'city_id' => 42, 'district' => 'Cihanbeyli' ],
            [ 'city_id' => 42, 'district' => 'Çumra' ],
            [ 'city_id' => 42, 'district' => 'Doğanhisar' ],
            [ 'city_id' => 42, 'district' => 'Ereğli / Konya' ],
            [ 'city_id' => 42, 'district' => 'Hadim' ],
            [ 'city_id' => 42, 'district' => 'Ilgın' ],
            [ 'city_id' => 42, 'district' => 'Kadınhanı' ],
            [ 'city_id' => 42, 'district' => 'Karapınar' ],
            [ 'city_id' => 42, 'district' => 'Kulu' ],
            [ 'city_id' => 42, 'district' => 'Sarayönü' ],
            [ 'city_id' => 42, 'district' => 'Seydişehir' ],
            [ 'city_id' => 42, 'district' => 'Yunak' ],
            [ 'city_id' => 42, 'district' => 'Akören' ],
            [ 'city_id' => 42, 'district' => 'Altınekin' ],
            [ 'city_id' => 42, 'district' => 'Derebucak' ],
            [ 'city_id' => 42, 'district' => 'Hüyük' ],
            [ 'city_id' => 42, 'district' => 'Karatay' ],
            [ 'city_id' => 42, 'district' => 'Meram' ],
            [ 'city_id' => 42, 'district' => 'Selçuklu' ],
            [ 'city_id' => 42, 'district' => 'Taşkent' ],
            [ 'city_id' => 42, 'district' => 'Ahırlı' ],
            [ 'city_id' => 42, 'district' => 'Çeltik' ],
            [ 'city_id' => 42, 'district' => 'Derbent' ],
            [ 'city_id' => 42, 'district' => 'Emirgazi' ],
            [ 'city_id' => 42, 'district' => 'Güneysınır' ],
            [ 'city_id' => 42, 'district' => 'Halkapınar' ],
            [ 'city_id' => 42, 'district' => 'Tuzlukçu' ],
            [ 'city_id' => 42, 'district' => 'Yalıhüyük' ],
            [ 'city_id' => 43, 'district' => 'Altıntaş' ],
            [ 'city_id' => 43, 'district' => 'Domaniç' ],
            [ 'city_id' => 43, 'district' => 'Emet' ],
            [ 'city_id' => 43, 'district' => 'Gediz' ],
            [ 'city_id' => 43, 'district' => 'Kütahya Merkez' ],
            [ 'city_id' => 43, 'district' => 'Simav' ],
            [ 'city_id' => 43, 'district' => 'Tavşanlı' ],
            [ 'city_id' => 43, 'district' => 'Aslanapa' ],
            [ 'city_id' => 43, 'district' => 'Dumlupınar' ],
            [ 'city_id' => 43, 'district' => 'Hisarcık' ],
            [ 'city_id' => 43, 'district' => 'Şaphane' ],
            [ 'city_id' => 43, 'district' => 'Çavdarhisar' ],
            [ 'city_id' => 43, 'district' => 'Pazarlar' ],
            [ 'city_id' => 44, 'district' => 'Akçadağ' ],
            [ 'city_id' => 44, 'district' => 'Arapgir' ],
            [ 'city_id' => 44, 'district' => 'Arguvan' ],
            [ 'city_id' => 44, 'district' => 'Darende' ],
            [ 'city_id' => 44, 'district' => 'Doğanşehir' ],
            [ 'city_id' => 44, 'district' => 'Hekimhan' ],
            [ 'city_id' => 44, 'district' => 'Malatya Merkez' ],
            [ 'city_id' => 44, 'district' => 'Pütürge' ],
            [ 'city_id' => 44, 'district' => 'Yeşilyurt / Malatya' ],
            [ 'city_id' => 44, 'district' => 'Battalgazi' ],
            [ 'city_id' => 44, 'district' => 'Doğanyol' ],
            [ 'city_id' => 44, 'district' => 'Kale / Malatya' ],
            [ 'city_id' => 44, 'district' => 'Kuluncak' ],
            [ 'city_id' => 44, 'district' => 'Yazıhan' ],
            [ 'city_id' => 45, 'district' => 'Akhisar' ],
            [ 'city_id' => 45, 'district' => 'Alaşehir' ],
            [ 'city_id' => 45, 'district' => 'Demirci' ],
            [ 'city_id' => 45, 'district' => 'Gördes' ],
            [ 'city_id' => 45, 'district' => 'Kırkağaç' ],
            [ 'city_id' => 45, 'district' => 'Kula' ],
            [ 'city_id' => 45, 'district' => 'Manisa Merkez' ],
            [ 'city_id' => 45, 'district' => 'Salihli' ],
            [ 'city_id' => 45, 'district' => 'Sarıgöl' ],
            [ 'city_id' => 45, 'district' => 'Saruhanlı' ],
            [ 'city_id' => 45, 'district' => 'Selendi' ],
            [ 'city_id' => 45, 'district' => 'Soma' ],
            [ 'city_id' => 45, 'district' => 'Turgutlu' ],
            [ 'city_id' => 45, 'district' => 'Ahmetli' ],
            [ 'city_id' => 45, 'district' => 'Gölmarmara' ],
            [ 'city_id' => 45, 'district' => 'Köprübaşı / Manisa' ],
            [ 'city_id' => 45, 'district' => 'Şehzadeler' ],
            [ 'city_id' => 45, 'district' => 'Yunusemre' ],
            [ 'city_id' => 46, 'district' => 'Afşin' ],
            [ 'city_id' => 46, 'district' => 'Andırın' ],
            [ 'city_id' => 46, 'district' => 'Elbistan' ],
            [ 'city_id' => 46, 'district' => 'Göksun' ],
            [ 'city_id' => 46, 'district' => 'Kahramanmaraş Merkez' ],
            [ 'city_id' => 46, 'district' => 'Pazarcık' ],
            [ 'city_id' => 46, 'district' => 'Türkoğlu' ],
            [ 'city_id' => 46, 'district' => 'Çağlayancerit' ],
            [ 'city_id' => 46, 'district' => 'Ekinözü' ],
            [ 'city_id' => 46, 'district' => 'Nurhak' ],
            [ 'city_id' => 46, 'district' => 'Dulkadiroğlu' ],
            [ 'city_id' => 46, 'district' => 'Onikişubat' ],
            [ 'city_id' => 47, 'district' => 'Derik' ],
            [ 'city_id' => 47, 'district' => 'Kızıltepe' ],
            [ 'city_id' => 47, 'district' => 'Mardin Merkez' ],
            [ 'city_id' => 47, 'district' => 'Mazıdağı' ],
            [ 'city_id' => 47, 'district' => 'Midyat' ],
            [ 'city_id' => 47, 'district' => 'Nusaybin' ],
            [ 'city_id' => 47, 'district' => 'Ömerli' ],
            [ 'city_id' => 47, 'district' => 'Savur' ],
            [ 'city_id' => 47, 'district' => 'Dargeçit' ],
            [ 'city_id' => 47, 'district' => 'Yeşilli' ],
            [ 'city_id' => 47, 'district' => 'Artuklu' ],
            [ 'city_id' => 48, 'district' => 'Bodrum' ],
            [ 'city_id' => 48, 'district' => 'Datça' ],
            [ 'city_id' => 48, 'district' => 'Fethiye' ],
            [ 'city_id' => 48, 'district' => 'Köyceğiz' ],
            [ 'city_id' => 48, 'district' => 'Marmaris' ],
            [ 'city_id' => 48, 'district' => 'Milas' ],
            [ 'city_id' => 48, 'district' => 'Muğla Merkez' ],
            [ 'city_id' => 48, 'district' => 'Ula' ],
            [ 'city_id' => 48, 'district' => 'Yatağan' ],
            [ 'city_id' => 48, 'district' => 'Dalaman' ],
            [ 'city_id' => 48, 'district' => 'Ortaca' ],
            [ 'city_id' => 48, 'district' => 'Kavaklıdere' ],
            [ 'city_id' => 48, 'district' => 'Menteşe' ],
            [ 'city_id' => 48, 'district' => 'Seydikemer' ],
            [ 'city_id' => 49, 'district' => 'Bulanık' ],
            [ 'city_id' => 49, 'district' => 'Malazgirt' ],
            [ 'city_id' => 49, 'district' => 'Muş Merkez' ],
            [ 'city_id' => 49, 'district' => 'Varto' ],
            [ 'city_id' => 49, 'district' => 'Hasköy' ],
            [ 'city_id' => 49, 'district' => 'Korkut' ],
            [ 'city_id' => 50, 'district' => 'Avanos' ],
            [ 'city_id' => 50, 'district' => 'Derinkuyu' ],
            [ 'city_id' => 50, 'district' => 'Gülşehir' ],
            [ 'city_id' => 50, 'district' => 'Hacıbektaş' ],
            [ 'city_id' => 50, 'district' => 'Kozaklı' ],
            [ 'city_id' => 50, 'district' => 'Nevşehir Merkez' ],
            [ 'city_id' => 50, 'district' => 'Ürgüp' ],
            [ 'city_id' => 50, 'district' => 'Acıgöl' ],
            [ 'city_id' => 51, 'district' => 'Bor' ],
            [ 'city_id' => 51, 'district' => 'Çamardı' ],
            [ 'city_id' => 51, 'district' => 'Niğde Merkez' ],
            [ 'city_id' => 51, 'district' => 'Ulukışla' ],
            [ 'city_id' => 51, 'district' => 'Altunhisar' ],
            [ 'city_id' => 51, 'district' => 'Çiftlik' ],
            [ 'city_id' => 52, 'district' => 'Akkuş' ],
            [ 'city_id' => 52, 'district' => 'Aybastı' ],
            [ 'city_id' => 52, 'district' => 'Fatsa' ],
            [ 'city_id' => 52, 'district' => 'Gölköy' ],
            [ 'city_id' => 52, 'district' => 'Korgan' ],
            [ 'city_id' => 52, 'district' => 'Kumru' ],
            [ 'city_id' => 52, 'district' => 'Mesudiye' ],
            [ 'city_id' => 52, 'district' => 'Ordu Merkez' ],
            [ 'city_id' => 52, 'district' => 'Perşembe' ],
            [ 'city_id' => 52, 'district' => 'Ulubey / Ordu' ],
            [ 'city_id' => 52, 'district' => 'Ünye' ],
            [ 'city_id' => 52, 'district' => 'Gülyalı' ],
            [ 'city_id' => 52, 'district' => 'Gürgentepe' ],
            [ 'city_id' => 52, 'district' => 'Çamaş' ],
            [ 'city_id' => 52, 'district' => 'Çatalpınar' ],
            [ 'city_id' => 52, 'district' => 'Çaybaşı' ],
            [ 'city_id' => 52, 'district' => 'İkizce' ],
            [ 'city_id' => 52, 'district' => 'Kabadüz' ],
            [ 'city_id' => 52, 'district' => 'Kabataş' ],
            [ 'city_id' => 52, 'district' => 'Altınordu' ],
            [ 'city_id' => 53, 'district' => 'Ardeşen' ],
            [ 'city_id' => 53, 'district' => 'Çamlıhemşin' ],
            [ 'city_id' => 53, 'district' => 'Çayeli' ],
            [ 'city_id' => 53, 'district' => 'Fındıklı' ],
            [ 'city_id' => 53, 'district' => 'İkizdere' ],
            [ 'city_id' => 53, 'district' => 'Kalkandere' ],
            [ 'city_id' => 53, 'district' => 'Pazar / Rize' ],
            [ 'city_id' => 53, 'district' => 'Rize Merkez' ],
            [ 'city_id' => 53, 'district' => 'Güneysu' ],
            [ 'city_id' => 53, 'district' => 'Derepazarı' ],
            [ 'city_id' => 53, 'district' => 'Hemşin' ],
            [ 'city_id' => 53, 'district' => 'İyidere' ],
            [ 'city_id' => 54, 'district' => 'Akyazı' ],
            [ 'city_id' => 54, 'district' => 'Geyve' ],
            [ 'city_id' => 54, 'district' => 'Hendek' ],
            [ 'city_id' => 54, 'district' => 'Karasu' ],
            [ 'city_id' => 54, 'district' => 'Kaynarca' ],
            [ 'city_id' => 54, 'district' => 'Sakarya Merkez' ],
            [ 'city_id' => 54, 'district' => 'Sapanca' ],
            [ 'city_id' => 54, 'district' => 'Kocaali' ],
            [ 'city_id' => 54, 'district' => 'Pamukova' ],
            [ 'city_id' => 54, 'district' => 'Taraklı' ],
            [ 'city_id' => 54, 'district' => 'Ferizli' ],
            [ 'city_id' => 54, 'district' => 'Karapürçek' ],
            [ 'city_id' => 54, 'district' => 'Söğütlü' ],
            [ 'city_id' => 54, 'district' => 'Adapazarı' ],
            [ 'city_id' => 54, 'district' => 'Arifiye' ],
            [ 'city_id' => 54, 'district' => 'Erenler' ],
            [ 'city_id' => 54, 'district' => 'Serdivan' ],
            [ 'city_id' => 55, 'district' => 'Alaçam' ],
            [ 'city_id' => 55, 'district' => 'Bafra' ],
            [ 'city_id' => 55, 'district' => 'Çarşamba' ],
            [ 'city_id' => 55, 'district' => 'Havza' ],
            [ 'city_id' => 55, 'district' => 'Kavak' ],
            [ 'city_id' => 55, 'district' => 'Ladik' ],
            [ 'city_id' => 55, 'district' => 'Samsun Merkez' ],
            [ 'city_id' => 55, 'district' => 'Terme' ],
            [ 'city_id' => 55, 'district' => 'Vezirköprü' ],
            [ 'city_id' => 55, 'district' => 'Asarcık' ],
            [ 'city_id' => 55, 'district' => '19 Mayıs' ],
            [ 'city_id' => 55, 'district' => 'Salıpazarı' ],
            [ 'city_id' => 55, 'district' => 'Tekkeköy' ],
            [ 'city_id' => 55, 'district' => 'Ayvacık / Samsun' ],
            [ 'city_id' => 55, 'district' => 'Yakakent' ],
            [ 'city_id' => 55, 'district' => 'Atakum' ],
            [ 'city_id' => 55, 'district' => 'Canik' ],
            [ 'city_id' => 55, 'district' => 'İlkadım' ],
            [ 'city_id' => 56, 'district' => 'Baykan' ],
            [ 'city_id' => 56, 'district' => 'Eruh' ],
            [ 'city_id' => 56, 'district' => 'Kurtalan' ],
            [ 'city_id' => 56, 'district' => 'Pervari' ],
            [ 'city_id' => 56, 'district' => 'Siirt Merkez' ],
            [ 'city_id' => 56, 'district' => 'Şirvan' ],
            [ 'city_id' => 56, 'district' => 'Tillo' ],
            [ 'city_id' => 57, 'district' => 'Ayancık' ],
            [ 'city_id' => 57, 'district' => 'Boyabat' ],
            [ 'city_id' => 57, 'district' => 'Durağan' ],
            [ 'city_id' => 57, 'district' => 'Erfelek' ],
            [ 'city_id' => 57, 'district' => 'Gerze' ],
            [ 'city_id' => 57, 'district' => 'Sinop Merkez' ],
            [ 'city_id' => 57, 'district' => 'Türkeli' ],
            [ 'city_id' => 57, 'district' => 'Dikmen' ],
            [ 'city_id' => 57, 'district' => 'Saraydüzü' ],
            [ 'city_id' => 58, 'district' => 'Divriği' ],
            [ 'city_id' => 58, 'district' => 'Gemerek' ],
            [ 'city_id' => 58, 'district' => 'Gürün' ],
            [ 'city_id' => 58, 'district' => 'Hafik' ],
            [ 'city_id' => 58, 'district' => 'İmranlı' ],
            [ 'city_id' => 58, 'district' => 'Kangal' ],
            [ 'city_id' => 58, 'district' => 'Koyulhisar' ],
            [ 'city_id' => 58, 'district' => 'Sivas Merkez' ],
            [ 'city_id' => 58, 'district' => 'Suşehri' ],
            [ 'city_id' => 58, 'district' => 'Şarkışla' ],
            [ 'city_id' => 58, 'district' => 'Yıldızeli' ],
            [ 'city_id' => 58, 'district' => 'Zara' ],
            [ 'city_id' => 58, 'district' => 'Akıncılar' ],
            [ 'city_id' => 58, 'district' => 'Altınyayla / Sivas' ],
            [ 'city_id' => 58, 'district' => 'Doğanşar' ],
            [ 'city_id' => 58, 'district' => 'Gölova' ],
            [ 'city_id' => 58, 'district' => 'Ulaş' ],
            [ 'city_id' => 59, 'district' => 'Çerkezköy' ],
            [ 'city_id' => 59, 'district' => 'Çorlu' ],
            [ 'city_id' => 59, 'district' => 'Hayrabolu' ],
            [ 'city_id' => 59, 'district' => 'Malkara' ],
            [ 'city_id' => 59, 'district' => 'Muratlı' ],
            [ 'city_id' => 59, 'district' => 'Saray / Tekirdağ' ],
            [ 'city_id' => 59, 'district' => 'Şarköy' ],
            [ 'city_id' => 59, 'district' => 'Tekirdağ Merkez' ],
            [ 'city_id' => 59, 'district' => 'Marmaraereğlisi' ],
            [ 'city_id' => 59, 'district' => 'Ergene' ],
            [ 'city_id' => 59, 'district' => 'Kapaklı' ],
            [ 'city_id' => 59, 'district' => 'Süleymanpaşa' ],
            [ 'city_id' => 60, 'district' => 'Almus' ],
            [ 'city_id' => 60, 'district' => 'Artova' ],
            [ 'city_id' => 60, 'district' => 'Erbaa' ],
            [ 'city_id' => 60, 'district' => 'Niksar' ],
            [ 'city_id' => 60, 'district' => 'Reşadiye' ],
            [ 'city_id' => 60, 'district' => 'Tokat Merkez' ],
            [ 'city_id' => 60, 'district' => 'Turhal' ],
            [ 'city_id' => 60, 'district' => 'Zile' ],
            [ 'city_id' => 60, 'district' => 'Pazar / Tokat' ],
            [ 'city_id' => 60, 'district' => 'Yeşilyurt / Tokat' ],
            [ 'city_id' => 60, 'district' => 'Başçiftlik' ],
            [ 'city_id' => 60, 'district' => 'Sulusaray' ],
            [ 'city_id' => 61, 'district' => 'Akçaabat' ],
            [ 'city_id' => 61, 'district' => 'Araklı' ],
            [ 'city_id' => 61, 'district' => 'Arsin' ],
            [ 'city_id' => 61, 'district' => 'Çaykara' ],
            [ 'city_id' => 61, 'district' => 'Maçka' ],
            [ 'city_id' => 61, 'district' => 'Of' ],
            [ 'city_id' => 61, 'district' => 'Sürmene' ],
            [ 'city_id' => 61, 'district' => 'Tonya' ],
            [ 'city_id' => 61, 'district' => 'Trabzon Merkez' ],
            [ 'city_id' => 61, 'district' => 'Vakfıkebir' ],
            [ 'city_id' => 61, 'district' => 'Yomra' ],
            [ 'city_id' => 61, 'district' => 'Beşikdüzü' ],
            [ 'city_id' => 61, 'district' => 'Şalpazarı' ],
            [ 'city_id' => 61, 'district' => 'Çarşıbaşı' ],
            [ 'city_id' => 61, 'district' => 'Dernekpazarı' ],
            [ 'city_id' => 61, 'district' => 'Düzköy' ],
            [ 'city_id' => 61, 'district' => 'Hayrat' ],
            [ 'city_id' => 61, 'district' => 'Köprübaşı / Trabzon' ],
            [ 'city_id' => 61, 'district' => 'Ortahisar' ],
            [ 'city_id' => 62, 'district' => 'Çemişgezek' ],
            [ 'city_id' => 62, 'district' => 'Hozat' ],
            [ 'city_id' => 62, 'district' => 'Mazgirt' ],
            [ 'city_id' => 62, 'district' => 'Nazımiye' ],
            [ 'city_id' => 62, 'district' => 'Ovacık / Tunceli' ],
            [ 'city_id' => 62, 'district' => 'Pertek' ],
            [ 'city_id' => 62, 'district' => 'Pülümür' ],
            [ 'city_id' => 62, 'district' => 'Tunceli Merkez' ],
            [ 'city_id' => 63, 'district' => 'Akçakale' ],
            [ 'city_id' => 63, 'district' => 'Birecik' ],
            [ 'city_id' => 63, 'district' => 'Bozova' ],
            [ 'city_id' => 63, 'district' => 'Ceylanpınar' ],
            [ 'city_id' => 63, 'district' => 'Halfeti' ],
            [ 'city_id' => 63, 'district' => 'Hilvan' ],
            [ 'city_id' => 63, 'district' => 'Siverek' ],
            [ 'city_id' => 63, 'district' => 'Suruç' ],
            [ 'city_id' => 63, 'district' => 'Şanlıurfa Merkez' ],
            [ 'city_id' => 63, 'district' => 'Viranşehir' ],
            [ 'city_id' => 63, 'district' => 'Harran' ],
            [ 'city_id' => 63, 'district' => 'Eyyübiye' ],
            [ 'city_id' => 63, 'district' => 'Haliliye' ],
            [ 'city_id' => 63, 'district' => 'Karaköprü' ],
            [ 'city_id' => 64, 'district' => 'Banaz' ],
            [ 'city_id' => 64, 'district' => 'Eşme' ],
            [ 'city_id' => 64, 'district' => 'Karahallı' ],
            [ 'city_id' => 64, 'district' => 'Sivaslı' ],
            [ 'city_id' => 64, 'district' => 'Ulubey / Uşak' ],
            [ 'city_id' => 64, 'district' => 'Uşak Merkez' ],
            [ 'city_id' => 65, 'district' => 'Başkale' ],
            [ 'city_id' => 65, 'district' => 'Çatak' ],
            [ 'city_id' => 65, 'district' => 'Erciş' ],
            [ 'city_id' => 65, 'district' => 'Gevaş' ],
            [ 'city_id' => 65, 'district' => 'Gürpınar' ],
            [ 'city_id' => 65, 'district' => 'Muradiye' ],
            [ 'city_id' => 65, 'district' => 'Özalp' ],
            [ 'city_id' => 65, 'district' => 'Van Merkez' ],
            [ 'city_id' => 65, 'district' => 'Bahçesaray' ],
            [ 'city_id' => 65, 'district' => 'Çaldıran' ],
            [ 'city_id' => 65, 'district' => 'Edremit / Van' ],
            [ 'city_id' => 65, 'district' => 'Saray / Van' ],
            [ 'city_id' => 65, 'district' => 'İpekyolu' ],
            [ 'city_id' => 65, 'district' => 'Tuşba' ],
            [ 'city_id' => 66, 'district' => 'Akdağmadeni' ],
            [ 'city_id' => 66, 'district' => 'Boğazlıyan' ],
            [ 'city_id' => 66, 'district' => 'Çayıralan' ],
            [ 'city_id' => 66, 'district' => 'Çekerek' ],
            [ 'city_id' => 66, 'district' => 'Sarıkaya' ],
            [ 'city_id' => 66, 'district' => 'Sorgun' ],
            [ 'city_id' => 66, 'district' => 'Şefaatli' ],
            [ 'city_id' => 66, 'district' => 'Yerköy' ],
            [ 'city_id' => 66, 'district' => 'Yozgat Merkez' ],
            [ 'city_id' => 66, 'district' => 'Aydıncık / Yozgat' ],
            [ 'city_id' => 66, 'district' => 'Çandır' ],
            [ 'city_id' => 66, 'district' => 'Kadışehri' ],
            [ 'city_id' => 66, 'district' => 'Saraykent' ],
            [ 'city_id' => 66, 'district' => 'Yenifakılı' ],
            [ 'city_id' => 67, 'district' => 'Çaycuma' ],
            [ 'city_id' => 67, 'district' => 'Devrek' ],
            [ 'city_id' => 67, 'district' => 'Ereğli / Zonguldak' ],
            [ 'city_id' => 67, 'district' => 'Zonguldak Merkez' ],
            [ 'city_id' => 67, 'district' => 'Alaplı' ],
            [ 'city_id' => 67, 'district' => 'Gökçebey' ],
            [ 'city_id' => 67, 'district' => 'Kilimli' ],
            [ 'city_id' => 67, 'district' => 'Kozlu' ],
            [ 'city_id' => 68, 'district' => 'Aksaray Merkez' ],
            [ 'city_id' => 68, 'district' => 'Ortaköy / Aksaray' ],
            [ 'city_id' => 68, 'district' => 'Ağaçören' ],
            [ 'city_id' => 68, 'district' => 'Güzelyurt' ],
            [ 'city_id' => 68, 'district' => 'Sarıyahşi' ],
            [ 'city_id' => 68, 'district' => 'Eskil' ],
            [ 'city_id' => 68, 'district' => 'Gülağaç' ],
            [ 'city_id' => 69, 'district' => 'Bayburt Merkez' ],
            [ 'city_id' => 69, 'district' => 'Aydıntepe' ],
            [ 'city_id' => 69, 'district' => 'Demirözü' ],
            [ 'city_id' => 70, 'district' => 'Ermenek' ],
            [ 'city_id' => 70, 'district' => 'Karaman Merkez' ],
            [ 'city_id' => 70, 'district' => 'Ayrancı' ],
            [ 'city_id' => 70, 'district' => 'Kazımkarabekir' ],
            [ 'city_id' => 70, 'district' => 'Başyayla' ],
            [ 'city_id' => 70, 'district' => 'Sarıveliler' ],
            [ 'city_id' => 71, 'district' => 'Delice' ],
            [ 'city_id' => 71, 'district' => 'Keskin' ],
            [ 'city_id' => 71, 'district' => 'Kırıkkale Merkez' ],
            [ 'city_id' => 71, 'district' => 'Sulakyurt' ],
            [ 'city_id' => 71, 'district' => 'Bahşili' ],
            [ 'city_id' => 71, 'district' => 'Balışeyh' ],
            [ 'city_id' => 71, 'district' => 'Çelebi' ],
            [ 'city_id' => 71, 'district' => 'Karakeçili' ],
            [ 'city_id' => 71, 'district' => 'Yahşihan' ],
            [ 'city_id' => 72, 'district' => 'Batman Merkez' ],
            [ 'city_id' => 72, 'district' => 'Beşiri' ],
            [ 'city_id' => 72, 'district' => 'Gercüş' ],
            [ 'city_id' => 72, 'district' => 'Kozluk' ],
            [ 'city_id' => 72, 'district' => 'Sason' ],
            [ 'city_id' => 72, 'district' => 'Hasankeyf' ],
            [ 'city_id' => 73, 'district' => 'Beytüşşebap' ],
            [ 'city_id' => 73, 'district' => 'Cizre' ],
            [ 'city_id' => 73, 'district' => 'İdil' ],
            [ 'city_id' => 73, 'district' => 'Silopi' ],
            [ 'city_id' => 73, 'district' => 'Şırnak Merkez' ],
            [ 'city_id' => 73, 'district' => 'Uludere' ],
            [ 'city_id' => 73, 'district' => 'Güçlükonak' ],
            [ 'city_id' => 74, 'district' => 'Bartın Merkez' ],
            [ 'city_id' => 74, 'district' => 'Kurucaşile' ],
            [ 'city_id' => 74, 'district' => 'Ulus' ],
            [ 'city_id' => 74, 'district' => 'Amasra' ],
            [ 'city_id' => 75, 'district' => 'Ardahan Merkez' ],
            [ 'city_id' => 75, 'district' => 'Çıldır' ],
            [ 'city_id' => 75, 'district' => 'Göle' ],
            [ 'city_id' => 75, 'district' => 'Hanak' ],
            [ 'city_id' => 75, 'district' => 'Posof' ],
            [ 'city_id' => 75, 'district' => 'Damal' ],
            [ 'city_id' => 76, 'district' => 'Aralık' ],
            [ 'city_id' => 76, 'district' => 'Iğdır Merkez' ],
            [ 'city_id' => 76, 'district' => 'Tuzluca' ],
            [ 'city_id' => 76, 'district' => 'Karakoyunlu' ],
            [ 'city_id' => 77, 'district' => 'Yalova Merkez' ],
            [ 'city_id' => 77, 'district' => 'Altınova' ],
            [ 'city_id' => 77, 'district' => 'Armutlu' ],
            [ 'city_id' => 77, 'district' => 'Çınarcık' ],
            [ 'city_id' => 77, 'district' => 'Çiftlikköy' ],
            [ 'city_id' => 77, 'district' => 'Termal' ],
            [ 'city_id' => 78, 'district' => 'Eflani' ],
            [ 'city_id' => 78, 'district' => 'Eskipazar' ],
            [ 'city_id' => 78, 'district' => 'Karabük Merkez' ],
            [ 'city_id' => 78, 'district' => 'Ovacık / Karabük' ],
            [ 'city_id' => 78, 'district' => 'Safranbolu' ],
            [ 'city_id' => 78, 'district' => 'Yenice / Karabük' ],
            [ 'city_id' => 79, 'district' => 'Kilis Merkez' ],
            [ 'city_id' => 79, 'district' => 'Elbeyli' ],
            [ 'city_id' => 79, 'district' => 'Musabeyli' ],
            [ 'city_id' => 79, 'district' => 'Polateli' ],
            [ 'city_id' => 80, 'district' => 'Bahçe' ],
            [ 'city_id' => 80, 'district' => 'Kadirli' ],
            [ 'city_id' => 80, 'district' => 'Osmaniye Merkez' ],
            [ 'city_id' => 80, 'district' => 'Düziçi' ],
            [ 'city_id' => 80, 'district' => 'Hasanbeyli' ],
            [ 'city_id' => 80, 'district' => 'Sumbas' ],
            [ 'city_id' => 80, 'district' => 'Toprakkale' ],
            [ 'city_id' => 81, 'district' => 'Akçakoca' ],
            [ 'city_id' => 81, 'district' => 'Düzce Merkez' ],
            [ 'city_id' => 81, 'district' => 'Yığılca' ],
            [ 'city_id' => 81, 'district' => 'Cumayeri' ],
            [ 'city_id' => 81, 'district' => 'Gölyaka' ],
            [ 'city_id' => 81, 'district' => 'Çilimli' ],
            [ 'city_id' => 81, 'district' => 'Gümüşova' ],
            [ 'city_id' => 81, 'district' => 'Kaynaşlı' ]
        ];

        DB::table('districts')->insert($districts);

    }
}
